In [11]:
#random forest model
#a RF model does not need feature scaling
#robust to weird feature distributions
#handles non-linear patterns
#pipeline is simpler compared to LR

In [12]:
import pandas as pd
from google.colab import drive
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [13]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:
tf1 = pd.read_parquet('/content/drive/MyDrive/AI4_Data/Processed/tf1_processed.parquet')
tf1.shape

(158158, 570)

In [15]:
#count real labels
tf1['label'].value_counts()

label
 1    63713
 0    52338
-1    42107
Name: count, dtype: int64

In [16]:
#remove unlabeled samples
tf1_clean = tf1[tf1['label'].isin([0,1])].copy()
tf1_clean['label'].value_counts()

label
1    63713
0    52338
Name: count, dtype: int64

In [17]:
#train/validation split
X = tf1_clean.drop(columns=['label'])
y = tf1_clean['label']

X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

X_train.shape, X_val.shape

((92840, 569), (23211, 569))

In [18]:
#import RF
from sklearn.ensemble import RandomForestClassifier

In [19]:
#define what RF is
rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

In [20]:
#train RF
rf_model.fit(X_train, y_train)

print("training complete.")

training complete.

In [ ]:
#make predictions

In [21]:
#predicted class labels (0 or 1)
rf_preds = rf_model.predict(X_val)

#predicted probabilities for positive class (m=1)
rf_probs = rf_model.predict_proba(X_val)[:,1]

print ("random forest predictions complete.")

random forest predictions complete.

In [22]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

rf_accuracy = accuracy_score(y_val, rf_preds)
rf_precision = precision_score(y_val, rf_preds)
rf_recall = recall_score(y_val, rf_preds)
rf_f1 = f1_score(y_val, rf_preds)
rf_roc_auc = roc_auc_score(y_val, rf_probs)
rf_cm = confusion_matrix(y_val, rf_preds)

print("random forest results")
print("...")
print("accuracy:", rf_accuracy)
print("precision:", rf_precision)
print("recall:", rf_recall)
print("f1 score:", rf_f1)
print("ROC-AUC:", rf_roc_auc)
print("\nconfusion matrix:\n", rf_cm)

random forest results
...
accuracy: 0.908577829477403
precision: 0.9311520662498985
recall: 0.9000235423369694
f1 score: 0.9153232242617717
ROC-AUC: 0.9718345257382575

confusion matrix:
 [[ 9620   848]
 [ 1274 11469]]

In [24]:
import joblib
joblib.dump(rf_model, '/content/drive/MyDrive/AI4_Data/Outputs/rf_baseline_model.joblib')

['/content/drive/MyDrive/AI4_Data/Outputs/rf_baseline_model.joblib']